services:
  # Service PHP / Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - maildev
    networks:
      - linko_network

  # Service MySQL
  db:
    image: mysql:8.0
    container_name: portfolio_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      # Définit le mot de passe root
      MYSQL_DATABASE: portfolio        # Crée la base de données automatiquement
      MYSQL_USER: Admin       # Crée un utilisateur standard
      MYSQL_PASSWORD: password4124         # Mot de passe de l'utilisateur laravel_user
    ports:
      - "3306:3306"
    networks:
      - linko_network
  # Service MailDev
  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: unless-stopped
    ports:
      - "1080:1080" # Interface web
      - "1025:1025" # Serveur SMTP
    networks:
      - linko_network
  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: portfolio_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - linko_network

  # Service Nginx
  webserver:
    image: nginx:alpine
    container_name: portfolio_webserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - linko_network

networks:
  linko_network:
    driver: bridge